server:
  port: 8080
eureka:
   client:
      service-url:
         default-zone: http://localhost:8761/eureka
okta:
  oauth2:
    issuer: https://dev-63954939.okta.com/oauth2/default
    client-id: 0oa7451v81v4EeUIE5d7
    client-secret: p5OyBKFMohHIzfjKPdPUb5lk9fdsr_iuwH7IxHUq
spring:
  banner:
     location: classpath:/auth-service/src/main/resources/banner.txt
  application:
      name: auth-service
  kafka:
     bootstrap-servers: kafka-service:9093
  cloud:
    stream:
      function:
        definition: userCreateSupplier
      bindings:
        userCreateSupplier-out-0:
          destination: user-event
      kafka:
        binder:
           replicationFactor: 1
        bindings:
          userCreateSupplier-out-0:
            producer:
              configuration:
                value:
                  serializer: org.apache.kafka.common.serialization.ByteArraySerializer
   