server:
  port: 8080
#eureka:
#   client:
#      service-url:
#         default-zone: http://localhost:8761/eureka
okta:
  oauth2:
    orgUrl: ${ORG_URL}
    sswsToken: ${SSWS_TOKEN}
    issuer: ${OKTA_ISSUER}
    client-id: ${CLIENT_ID}
    client-secret: ${CLIENT_SECRET}
spring:
  banner:
     location: classpath:/auth-service/src/main/resources/banner.txt
  application:
      name: auth-service
  kafka:
     bootstrap-servers: ${KAFKA_URL}
  cloud:
    stream:
      function:
        definition: userCreateSupplier
      bindings:
        userCreateSupplier-out-0:
          destination: user-event
      kafka:
        binder:
           replicationFactor: 1
        bindings:
          userCreateSupplier-out-0:
            producer:
              configuration:
                value:
                  serializer: org.apache.kafka.common.serialization.ByteArraySerializer
   