name: Build and Publish Docker Images
on: 
   push: 
      branches:
         - main
jobs:
   build:
      runs-on: ubuntu-latest
      steps:
         - name: GIT Checkout
           uses: actions/checkout@v2
         - name: Set up JDK
           uses: actions/setup-java@v1
           with:
              java-version: 1.11
         - name: Build with Maven
           run: mvn clean install
         - name: Login to Github Container Repository
           uses: docker/login-action@v1
           with: 
              registry: ghcr.io
              username: ${{ github.actor }}
              password: ${{ secrets.GITHUB_TOKEN}}
              repository: ghcr.io/banerjee-ronitb
         - name: Publish to Github Container Repository
           run: |
               docker build . --tag ghcr.io/banerjee-ronitb/auth-service:latest
               docker build . --tag ghcr.io/banerjee-ronitb/auth-service:${{github.run_number}}
               docker push ghcr.io/banerjee-ronitb/auth-service:latest
               docker push ghcr.io/banerjee-ronitb/auth-service:${{github.run_number}}
            